### ISSUE TITLE
macOS 10.15.7. Version 

### ISSUE THREAD

**Issue by StephanTe** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#1]
Hello,

> You have macOS 10.15.7. The application requires macOS 11.0 or later.

Is there any chance to get SwiftPlantUML for my version?

**Comment by MarcoEidinger** [comment]
Hi @StephanTe ,

I believe this should be possible as the underlying https://github.com/MarcoEidinger/SwiftPlantUML does not require macOS 11.0

You can try to change the deployment target in the Xcode project file, build locally and see if you get any issues when using the extension.

In the meantime, I will look into how I can verify it (maybe via CI/CD as my personal Mac does not run on 10.5.7) before doing the change and publish a new release.

**Comment by muhsayd** [comment]
When tried to build towards MacOS 10.15.7 I've got these issues:

```
@available(OSX 11.0, *)
@main                                                                        'main()' is only available in macOS 11.0 or newer
struct SwiftPlantUMLAppApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```
[Screenshot](https://prnt.sc/10wm9qy)

**Comment by MarcoEidinger** [comment]
Hi @muhsayd , thanks for the information. I did necessary code changes in branch [macOS1015](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/tree/macOS1015) so that app can be compiled for deployment target 10.15.

Please try to build from branch [macOS1015](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/tree/macOS1015) and install the Xcode Extension.

I'll try to verify this on a macOS 10.15 machine myself in the next couple of days.

**Comment by storymx** [comment]
@MarcoEidinger  is there any update by any chance for OSX 10.15.7 ?.

I can't upgrade since my computer is managed by my employer, they assign when I can update my OS remotely, also I couldn't Make it compile for 10.15.7

Thanks.

**Comment by MarcoEidinger** [comment]
I was able to obtain a machine with macOS 10.5.7 so hopefully in the next days I can share an app version working for 10.5.7

**Comment by MarcoEidinger** [comment]
Hi @storymx, @muhsayd , @StephanTe, this app version should work for macOS 10.5.7

- Unpack [SwiftPlantUMLApp.zip](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/files/6859503/SwiftPlantUMLApp.zip)
- Copy *SwiftPlantUML* to your *Applications* folder.
- Launch *SwiftPlantUML* once. You can close it immediately afterwards (i.e. Quit from Dock).
- Go to <kbd>System Preferences</kbd> > <kbd>Extensions</kbd> > <kbd>Xcode Source Editor</kbd> > select <kbd>SwiftPlantUML</kbd>

It works on my machines (macOS 10.5.7 and macOS 11) but if one of you could cross-check on your machine that would be awesome. Once I have confirmation I will push my changes create a GitHub release.

Cheers,
Marco
