### ISSUE TITLE
Menu does not show in the Xcode while run this project

### ISSUE THREAD

**Issue by James-Chi-Jie** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#11]
I clone this code, select `sourceeditorextesion` then run it, but the new launch xcode does not show the menu, I have no idea why

**Comment by MarcoEidinger** [comment]
You don't have to build from source. Follow [installation guide](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension#installation). If you want to run from source and debug then you have use correct certificates. That's the reason why menu doesn't show up for you.
