### ISSUE TITLE
Can multiple language annotations be supported?

### ISSUE THREAD

**Issue by anyuechao** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#15]
When I write Chinese Notes，It'll be garbled
<img width="1099" alt="WeChate0975d95245d4bdc48548aa0477b0540" src="https://user-images.githubusercontent.com/14137536/157200606-6f2cc493-a25c-40af-a2b4-904bf18f1121.png">
.

**Comment by MarcoEidinger** [comment]
Hi @anyuechao,

the PlantUML language [supports Unicode](https://plantuml.com/unicode). It seems that the specific [planttext.com](https://www.planttext.com/) server does not.

I filed a bug report [here and](https://blog.planttext.com/forums/forum/bug-reports/) and I recommend that you do the same. I don't know own that server.

I am aware of a different server which does support Unicode in PlantUML textual diagrams. Hence my recommendation is to copy-paste your diagrams containing Chinese characters into [here](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)

Cheers,
Marco
