### ISSUE TITLE
The application safari is not open anymore

### ISSUE THREAD

**Issue by zhouhao27** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#16]
Got this error message:

> The application "Safari" is not open anymore.

**Comment by MarcoEidinger** [comment]
I am unable to reproduce the issue you encounter. I run 1.3.0 on macOS 12.3.1 with Xcode 13.3. The extension essentially makes use of [`NSWorkspace.shared.open`](https://github.com/MarcoEidinger/SwiftPlantUML/blob/266a1d61b51b41b8c39b257103e6438615a7d8a2/Sources/SwiftPlantUMLFramework/Presenting/PlantUMLBrowserPresenter.swift#L36) and tries to open a URL. You have to have an app for handling and opening http URLs.

Please check if Safari generally works on your machine, if this AppKit API works for you and you might want to check out resources like [How to Fix "The Application Preview/Safari Is Not Open Anymore"](https://recoverit.wondershare.com/mac-tips/the-application-is-not-open-anymore.html) for help.
