### ISSUE TITLE
Multiple files support

### ISSUE THREAD

**Issue by ReDetection** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#17]
Hi. I guess many projects have just a single class per file. I guess it would be really messy to have everything in one file. ;)

So my question would be: is it possible to include several files into the output? If yes, what do we need to improve in the existing code? I would appreciate some suggestions or roadmap

**Comment by MarcoEidinger** [comment]
Nearly all Xcode Source Code Extensions do operate on a single file only. To generate a UML diagram based on multiple source files please use the command-line tool https://github.com/MarcoEidinger/SwiftPlantUML and please make sure to check out its configuration options, e.g.

- include/exclude files (wildcards supported)
- include/exclude elements by name (wildcards supported)
- limit elements and members bases on their access level, e.g. show only `public` types
- hide extensions
- hide member access level attribute
- configure styles, use [skin parameters](https://plantuml.com/skinparam) and even include external files for theming (e.g. [PUML Themes](https://bschwarz.github.io/puml-themes/))
- exclude inheritance relationships based on parent (wildcards supported), e.g. do not show inheritance to `Codable`

This will help to focus on the actual interesting stuff. Depending on the number of input files you might end with a large diagram even by filtering out certain entities. Online tools like PlantText do not support large diagrams properly so please check out my recommendations on https://github.com/MarcoEidinger/SwiftPlantUML#large-diagrams as you will still be able to generate large files locally
