### ISSUE TITLE
The command "Open editable diagram in browser" is still busy

### ISSUE THREAD

**Issue by yri066** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#2]
When trying to create a diagram, Xcode displays the message: The command "Open editable diagram in browser" is still busy <img width="404" alt="image" src="https://user-images.githubusercontent.com/26645205/118175058-455fb300-b438-11eb-83be-e1690f507658.png">

**Comment by KimTaeHyeong17** [comment]
![image](https://user-images.githubusercontent.com/37135317/118424310-f77dd000-b701-11eb-9b59-cd3c964e1885.png)
same issue here

**Comment by MarcoEidinger** [comment]
I encountered this issue initially only once. It looked to me that Xcode Source Code Extension initialization might be slow. Once I waited (and then I believed I restarted Xcode but I am not sure) and tried again it worked fine. Does this work for you? If not can you name your OS and Xcode versions and I'll try to see what can be done

**Comment by dmytro-kushnir** [comment]
hello @MarcoEidinger , the same situation happens to me. I'm using last OS and the last Xcode. Reload didn't helped

**Comment by MarcoEidinger** [comment]
@DIma-Kush you might need to wait up to 45 seconds for the very first time. If this does not help please let know what is exact OS and Xcode version you are using.

**Comment by dmytro-kushnir** [comment]
well, i waited 3 hours.. and nothing heppened :-)
Big Sur 11.5.2

XCode 12.5.1

**Comment by MarcoEidinger** [comment]
@DIma-Kush do you see a crash report for XPC service when opening the Console app on MacOS? Example:

<img width="1726" alt="CrashReportXPCServiceExample" src="https://user-images.githubusercontent.com/4176826/134083329-722a101a-4ec6-428b-9ee5-bcffec0784a8.png">

If you see such crash report related to `fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed` please check the installation path of Xcode. If it's installed under `/Applications/Xcode.app`, please run:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above with the location where you've installed Xcode.
