### ISSUE TITLE
Version 1.4.0 fails to open showing popup error

### ISSUE THREAD

**Issue by kikeenrique** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#20]
After download and installing in applications, trying to run the app shows a popup error.
`“SwiftPlantUMLApp” is damaged and can’t be opened. You should move it to the Bin.`

Here are some of the app messages seen in console.log, pointing towards a provision profile error.
```
Provisioning Profile Validation: profile '6V66CC3AN6.us.eidinger.SwiftPlantUML' is not provisioned for this device 
embedded provisioning profile not valid: file:///Applications/SwiftPlantUMLApp.app/Contents/embedded.provisionprofile error: Error Domain=CPProfileManager Code=-212 "Provisioning profile does not allow this device." UserInfo={NSLocalizedDescription=Provisioning profile does not allow this device.}
Disallowing us.eidinger.SwiftPlantUML because no eligible provisioning profiles found
mac_vnode_check_signature: /Applications/SwiftPlantUMLApp.app/Contents/MacOS/SwiftPlantUMLApp: code signature validation failed fatally: When validating /Applications/SwiftPlantUMLApp.app/Contents/MacOS/SwiftPlantUMLApp:
  Code has restricted entitlements, but the validation of its code signature failed.
Unsatisfied Entitlements:
```

I'm using version 1.4.0 on macOS Ventura 13.1 (22C65)

**Comment by MarcoEidinger** [comment]
Damn it, I forgot to sign the archive with my Developer ID. I will upload a correct 1.4.1 version soon

Thank you for reporting it!

**Comment by MarcoEidinger** [comment]
I created release 1.4.1, and you can download the app binary from [here](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/releases/tag/1.4.1)

Homebrew update is pending: https://github.com/Homebrew/homebrew-cask/pull/139292

**Comment by MarcoEidinger** [comment]
Version 1.4.1 is also available on Homebrew now.

if you still face issues with that new version then please let me know
