### ISSUE TITLE
[Bug] Syntax error in generated plantuml script

### ISSUE THREAD

**Issue by mrezabayat** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#29]
When trying to generate the class diagram of `AVFoundation.AVAsset`, I get the following error:

![image](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/assets/32814496/0bf4ec66-f2f5-4f60-879b-deeca5d2d189)

**Comment by MarcoEidinger** [comment]
Fixed with https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/releases/tag/1.6.0
