### ISSUE TITLE
Multiple swift files

### ISSUE THREAD

**Issue by Axort** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#3]
Is it possible to select multiple swift files and generate a diagram for all those files? Works like a charm for one file...

**Comment by MarcoEidinger** [comment]
Nearly all Xcode Source Code Extensions do operate on a single file only. To generate a UML diagram based on multiple source files please use the command-line tool https://github.com/MarcoEidinger/SwiftPlantUML and please make sure to check out its configuration options, e.g.

- include/exclude files (wildcards supported)
- include/exclude elements by name (wildcards supported)
- limit elements and members bases on their access level, e.g. show only `public` types
- hide extensions
- hide member access level attribute
- configure styles, use [skin parameters](https://plantuml.com/skinparam) and even include external files for theming (e.g. [PUML Themes](https://bschwarz.github.io/puml-themes/))
- exclude inheritance relationships based on parent (wildcards supported), e.g. do not show inheritance to `Codable`

This will help to focus on the actual interesting stuff. Depending on the number of input files you might end with a large diagram even by filtering out certain entities. Online tools like PlantText do not support large diagrams properly so please check out my recommendations on https://github.com/MarcoEidinger/SwiftPlantUML#large-diagrams as you will still be able to generate large files locally

**Comment by Axort** [comment]
Thank you, I ended up using the command-line tool, works like a charm! I thought it was possible for Xcode Source Code Extension to operate on multiple files, hope it's possible in the future.
