### ISSUE TITLE
The app does not work on macOS 10.15.7

### ISSUE THREAD

**Issue by YuriiLokhmatovGitHub** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#4]
Is it possible to rebuild the app to support old mac os?
In my case I got the following error:
You can’t use this version of the application “SwiftPlantUMLApp.app” with this version of macOS.
You have macOS 10.15.7. The application requires macOS 11.0 or later.

**Comment by MarcoEidinger** [comment]
Hi @YuriiLokhmatovGitHub , I did necessary code changes in branch [macOS1015](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/tree/macOS1015) so that app can be compiled for deployment target 10.15.

Please try to build from branch [macOS1015](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/tree/macOS1015) and install the Xcode Extension.

**Comment by YuriiLokhmatovGitHub** [comment]
Thank you very much Marco.
I checked it out and build. On 1st run I got the following error:
No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
Then I set NSPrincipalClass = NSApplication in the plist.info file.
After that the app could launch, there was its window.
Though the issue is that there is no Xcode Source Editor in the settings. I could see such an option on my newer mac running Big Sur, but it looks like I am out of luck on my old mac. Or maybe my Xcode 12.3 does not have such an option.

Any way thank you for your time.
Sincerely,
yurii.

**Comment by emretufekci** [comment]
Successfully built and run app from 1015 branch.
But same as @YuriiLokhmatovGitHub there is no label as Xcode Source Editor in the Extensions.
MacOS 10.15.7
XCode Version 12.4

**Comment by MarcoEidinger** [comment]
Hi @YuriiLokhmatovGitHub and @emretufekci,

the above version app version below should work for macOS 10.5.7

- Unpack [SwiftPlantUMLApp.zip](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension/files/6859503/SwiftPlantUMLApp.zip)
- Copy *SwiftPlantUML* to your *Applications* folder.
- Launch *SwiftPlantUML* once. You can close it immediately afterwards (i.e. Quit from Dock).
- Go to <kbd>System Preferences</kbd> > <kbd>Extensions</kbd> > <kbd>Xcode Source Editor</kbd> > select <kbd>SwiftPlantUML</kbd>

It works on my machines (macOS 10.5.7 and macOS 11) but if one of you could cross-check on your machine that would be awesome. Once I have confirmation I will push my changes create a GitHub release.

Cheers,
Marco
