### ISSUE TITLE
[Feature Request] support ObjectiveC

### ISSUE THREAD

**Issue by mcry416** [MarcoEidinger/SwiftPlantUML-Xcode-Extension#7]
It's awful to maintain a framework of 90,000 lines of code...And this framework is no document and just have a little annotion. How i wish u supported oc...

**Comment by MarcoEidinger** [comment]
Hi @mcry416, thanks for checking out this Xcode extension and I am sorry to hear that it cannot help with your Objective-C framework. I started this open-source project (and the underlying command-line tool `SwiftPlantUML`) aiming to cover Swift sources only.

Cheers,
Marco
